CREATE TABLE account_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    starting_balance NUMERIC(18,2) NOT NULL,
    risk_percent NUMERIC(8,4) NOT NULL,
    currency VARCHAR(5),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_account_settings_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_account_settings_user_id ON account_settings(user_id);
