CREATE TABLE cashflows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    amount_money NUMERIC(18,2) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_cashflows_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_cashflows_user_occurred_at ON cashflows(user_id, occurred_at);
