CREATE TABLE trades (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        symbol VARCHAR(20) NOT NULL,
                        direction VARCHAR(10) NOT NULL,
                        entry_price DECIMAL(19,5),
                        created_at TIMESTAMP NOT NULL
);
